name:                haskell-lsp-client
version:             0.0.0.1
synopsis:            A haskell library to build your own haskell-lsp client.
homepage:            https://github.com/noughtmare/haskell-lsp-client#readme
license:             GPL-2
author:              Jaro Reinders
maintainer:          noughtmare@openmailbox.org
copyright:           2017 Jaro Reinders
category:            Language, Protocol, Development
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - haskell-lsp

library:
  source-dirs:        src
  exposed-modules:    Client
  dependencies:
    - aeson
    - data-default
    - lens
    - bytestring
    - process
    - stm
    - attoparsec
    - containers
    - transformers
    - text

executables:
  haskell-lsp-client:
    dependencies:
      - haskell-lsp-client
    source-dirs:      app
    main:             Main.hs
    when:
      - condition: os(windows)
        then:
          dependencies:
            - Win32
        else:
          dependencies:
            - unix